version: '3'

services:
  php-fpm:
    container_name: auth_task_php
    build:
      context: ./php-fpm

  nginx:
    image: library/nginx:1.19.3
    container_name: auth_task_nginx
    volumes:
      - "./nginx:/etc/nginx/conf.d"
    depends_on:
      - php-fpm
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"

  mysql:
    image: library/mysql:8.0.22
    container_name: auth_task_mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"